from typing import Any

class LoadedModel:
    def predict(self, source: Any) -> Any: ...
    def crop(self, source: Any) -> Any: ...
    def export_dataset(self, output_path: str, format: str, *, source: str = ..., classes: list = ..., **kwargs: Any) -> Any: ...
    def unload(self) -> None: ...
    def warmup(self) -> None: ...
    def help(self) -> None: ...
    def export_config(self, output_path: str) -> None: ...

def load(key_or_path: str, **kwargs: Any) -> LoadedModel: ...
def register(model_key: str, model_path: str, backend: str, task: str, **kwargs: Any) -> str: ...
def register_file(file_path: str) -> str: ...
